manifest = "6365d5a92b3d1c9a77c410a5b537b38fb3f9a53be6b4832fe4c2baa13038037a"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container-hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
target = "//:predef"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart-ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type-traits"

[[dependency]]
package = "github.com/buckaroo-pm/icu4c"
target = "//:icu4c"

[[lock]]
name = "github.com/buckaroo-pm/boost-align"
version = "branch=master"
revision = "cb3c7a31931f9f02b3c663fa96f208c4f9055a44"

[[lock]]
name = "github.com/buckaroo-pm/boost-assert"
version = "branch=master"
revision = "cae7816110ba208a2290d02d128594e8809c9075"

[[lock]]
name = "github.com/buckaroo-pm/boost-config"
version = "branch=master"
revision = "f2f2d0d85496b72eeff1186518deb7e23c757bfd"

[[lock]]
name = "github.com/buckaroo-pm/boost-container_hash"
version = "branch=master"
revision = "9446eb516e717ae9c80bc89768a8d1160bcf6887"

[[lock]]
name = "github.com/buckaroo-pm/boost-core"
version = "branch=master"
revision = "10b589cb4aea4ca823237059f104cbfdd09b0f0e"

[[lock]]
name = "github.com/buckaroo-pm/boost-detail"
version = "branch=master"
revision = "94aa5268c1a74468be94b40afd730aea1730ceab"

[[lock]]
name = "github.com/buckaroo-pm/boost-exception"
version = "branch=master"
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[[lock]]
name = "github.com/buckaroo-pm/boost-integer"
version = "branch=master"
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[[lock]]
name = "github.com/buckaroo-pm/boost-iterator"
version = "branch=master"
revision = "c84fc34d0f6386edb15b0cb854a12864b6f15232"

[[lock]]
name = "github.com/buckaroo-pm/boost-move"
version = "branch=master"
revision = "183c4c120078cc80bdc9fd4089d911aecd922aac"

[[lock]]
name = "github.com/buckaroo-pm/boost-mpl"
version = "branch=master"
revision = "4c91f620f270414ceb5c3dbf3419a4f6ffe38c1e"

[[lock]]
name = "github.com/buckaroo-pm/boost-predef"
version = "branch=master"
revision = "73def0812b7235e0312079c729342787819bf1d5"

[[lock]]
name = "github.com/buckaroo-pm/boost-preprocessor"
version = "branch=master"
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[[lock]]
name = "github.com/buckaroo-pm/boost-smart_ptr"
version = "branch=master"
revision = "360ba641a719a115373a2721b169086029fb4358"

[[lock]]
name = "github.com/buckaroo-pm/boost-static_assert"
version = "branch=master"
revision = "4b9da4628bc69ad0e9b244d3ec885f2eadac95d8"

[[lock]]
name = "github.com/buckaroo-pm/boost-throw_exception"
version = "branch=master"
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[[lock]]
name = "github.com/buckaroo-pm/boost-type_traits"
version = "branch=master"
revision = "a34caf51f831ffb77d1057c668b5db620863d191"

[[lock]]
name = "github.com/buckaroo-pm/boost-utility"
version = "branch=master"
revision = "57aa216434800315c9cd2664169e444e3070a677"

[[lock]]
name = "github.com/buckaroo-pm/icu4c"
version = "branch=master"
revision = "d6803681f02ef9395665d4db6e84a4416a679bc3"
