manifest = "71b9e9d83b3e733178fc44fb7a6b583583d4a246213a3165627f59a6735ffc98"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.26.0" ]
revision = "abadb06fe73f9d1389aebfa0cb921fdd419aefc6"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.26.0" ]
revision = "015ed90656413825c45ff8a9bd54ec3ccb04842a"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.26.0" ]
revision = "ddf865e3b9f8a440b82629e66f55b011852a1614"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.26.0" ]
revision = "55e38f7c9a5081b6a2a98bb55f152ccd7f901a28"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.26.0" ]
revision = "7e5f9bb71d5efaa0b3107923793b140ddf3bfd6b"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.26.0" ]
revision = "b1d5087cb7c4773b0e9504482bd71333e5f6b737"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.26.0" ]
revision = "5527cd09c13d6678484d033c7f99dc6423d35e0d"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.26.0" ]
revision = "9e1862d0b873a90a79dcaf6f58aea1eac5f6ce88"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.26.0" ]
revision = "1a6146b132abdd55d5749760b371c779b2487982"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.26.0" ]
revision = "310ba15a06ac120b1b01f821d59a65eac062e348"
