manifest = "b6f2092e9726f5e91143d70696415c6cba0ad0e156ec6fbd7dbee4bfb1a6067e"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.47.0" ]
revision = "f6585b1993077d3de95ebcf766e3346b8aebb490"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.47.0" ]
revision = "3bf7c01d87539972b79b44087b2fc06fac79f97e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.47.0" ]
revision = "f39e5671b0d09010441b6549031deb68b7c75d44"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.47.0" ]
revision = "32eb9a6b12b5b39a766f8e722630b1dcdb2b385b"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.47.0" ]
revision = "c0cbf0c7044a075d52de530becacbe107da297a6"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.47.0" ]
revision = "cb8e48d0792e765a836b860ca4cd369d614afb36"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.47.0" ]
revision = "5b15e9b0092d3fccfb29c8baa352116f4c4575bd"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.47.0" ]
revision = "a10aeaf3d41bcfb604ae3d55df0842775df7646c"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.47.0" ]
revision = "b17cd5bfcc8eb6cde44203dde758b9776586a75a"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.47.0" ]
revision = "4c0ca7efafeb92fef2e725bcdebebc4173757633"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.47.0" ]
revision = "f819363b8527a9d718c3f170e44d3a54ed618749"
