manifest = "6f85876582f44dfb1c1ddc3823e1f3412eb6e5cf072703b22af240127dcf0f08"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.42.0" ]
revision = "bdbfd4f7cb2eb6f0a1d87672c0564f4909c4cb20"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.42.0" ]
revision = "5984095f0679a0334bd01d07a9ab1d7470cff18d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.42.0" ]
revision = "782ecf1ed3fb2e1eecf9b7cc91c596886d6f2acf"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.42.0" ]
revision = "32665b4a77378e96b1fd6ffb722d75c514f8122e"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.42.0" ]
revision = "8da9ed1fd5f551afeff13c5cc9b198116538886d"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.42.0" ]
revision = "833ab463d326c206e8cffec6aef1641f293448eb"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.42.0" ]
revision = "ad64e4e9f85cad0ed501c3eaf0faba2a9bfc3dc3"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.42.0" ]
revision = "ab771387589baa34e920f55b705793ea721f6526"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.42.0" ]
revision = "12ae8c5bf22e2da1edfcf02390b69d59c25c1001"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.42.0" ]
revision = "c303472af8c7e5744a3eaa1799f2ceb7014f4c51"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.42.0" ]
revision = "5ede30fc16f5822487be1b02337ba414ef4aae3c"
