manifest = "7af7f902fc8d4b82073f0f391e001cda018e96f1810d76d62f8fc255cee06a1f"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
target = "//:predef"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw_exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.65.0" ]
revision = "453245029ce7cfefe674c6c8cdac5d77ce73a55a"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.0" ]
revision = "d464187703a522223f9f3b01b4fbe8f8ae05fad6"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.0" ]
revision = "7268ab966b715d5702f1a2b98990626f1c193e6f"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.65.0" ]
revision = "c1e2be56b42af4b31b65a707e9548c543a96f420"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.0" ]
revision = "296264e87d794813a2c6681e56ca783560d4961d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.0" ]
revision = "2c6eae3c5a1b1278f35ea09e2df05f59c9303b12"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.65.0" ]
revision = "a9d8e79625f06fc6c7f4cf0408281bf95ac7be8e"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.65.0" ]
revision = "e513f6bb7a23184f77e6830601f6d5ef531c2c05"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.65.0" ]
revision = "10d8b39dee347d258683a41cb05a5d7be3a6493d"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.65.0" ]
revision = "a9ae50c688feed64d80487e2ec9f607fb35b5c1e"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.65.0" ]
revision = "3172b2bc9944fe34498a2b5ee318d4ea1499f04e"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.65.0" ]
revision = "0b7783052153c7145186017373319be29c4d1139"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.65.0" ]
revision = "312cb1699e9fbeb0ee859791f57290f6196a0eef"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.65.0" ]
revision = "61d271ef650eebfb79c29312a7a2f4dfd30324e6"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.65.0" ]
revision = "287f9aba51b4f6f6209d528d12918f048d940512"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.65.0" ]
revision = "950f4acddb2f565bb8161f839d7109479dae8977"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.0" ]
revision = "aa3a78164219356601785bc66c9fc70cac122ca3"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.65.0" ]
revision = "5c8b3f881967e39e3de946e321c37890d7588dba"
