manifest = "9e0b15955b77bc738884d77c3c68c03e4771baf7c5456637b4a2de14bb1448bb"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.39.0" ]
revision = "8d2669c973073bf1be4238a318c2784dd0999630"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.39.0" ]
revision = "50901969f4aae62a8b89d367c3fa081dc3052d7d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.39.0" ]
revision = "478a355bb52452bc27d16e2b68cf6677e09f3c96"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.39.0" ]
revision = "b7532201aec046e3b320266f7e5fd73f3d972d5e"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.39.0" ]
revision = "95158e066ba147c3d3c392f20ce8e64b86cd4f33"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.39.0" ]
revision = "2ae6217c88649cc02ab2a5f35b493724c7d9c597"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.39.0" ]
revision = "87e9eb41400a0eb04cfb81af1be42d1179b09b8b"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.39.0" ]
revision = "f97dd9d723a32cca358afd134f67eb789777ddf7"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.39.0" ]
revision = "aa9b48173569be31a060373000a54287e15422b8"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.39.0" ]
revision = "a5813a4400771cfafcf9d06f8b9dfddb3119ade8"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.39.0" ]
revision = "ac39e74ef9ca023c9780279df0bf89ca68cc64e9"
