manifest = "ea3b9828c2ebabd8094c979cff960fd668c61d88923bac5eacb2d998867d23c8"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.33.1" ]
revision = "fc0cda2c8601a5e6f1371a7d8f5f6152c73d8ad6"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.33.1" ]
revision = "dbe733553aeb9649363a64837fd6277a862a687d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.33.1" ]
revision = "163dee0104360b973f2b5b5dd4f786b991418a90"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.33.1" ]
revision = "d960d4cc76752d05685e8bee42ad289c1ef92330"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.33.1" ]
revision = "aefa444e5978847f3cee6cbe66e6ad3706388ce1"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.33.1" ]
revision = "db17ec9287b6da60bd80275fb2ff1d6ddc725ce0"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.33.1" ]
revision = "7a19606a1ccef0702ac61ba19d5e4bbe759c8949"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.33.1" ]
revision = "bffbfb1ac9c3dcd00b88fcd04f3a10e5d3d087ad"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.33.1" ]
revision = "af7fe0371043059d6c425a7f06d75e1c367e5559"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.33.1" ]
revision = "e34ef325b7e71252bb28959addee694f692154c5"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.33.1" ]
revision = "4d4141c4a8d814be8d17deae5fb6eb18b71b29a6"
