targets = ["//:regex"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
version = "1.34.1"