manifest = "adf9938601addf0bd0b2585491bbab35f680b65bf90833bacf17fe27ffc26308"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.18.2" ]
revision = "2bf83561dbe29c6a2f97e701b97009e21c960172"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.18.2" ]
revision = "ae71412f8dc1f0c1d485f64f9a504661765a3924"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.18.2" ]
revision = "d8760c9173c351453b4512c800eae5a663b3c6fb"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.18.2" ]
revision = "427d3837869a9ed7e226b6eb44edaf214574807f"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.18.2" ]
revision = "9b86bb65f1f8ae2c39fcaeb6f2d37e34da3714c0"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.18.2" ]
revision = "371ed47479c9e727f644a2343a1bee14d226ccd2"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.18.2" ]
revision = "7350f586ec6339dab6ed200a5eec7d0d1b0b5431"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.18.2" ]
revision = "33d92d4b9cd734777f84d6743ae40f983934f409"
