manifest = "8b236f316ee1e3e9f62999cd8f2fb726e4a900d0caeb9b5ba7ae38b6b3aa41b6"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.34.0" ]
revision = "a826516fbfc9407906d7407d5efb9f0f849fed22"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.34.0" ]
revision = "8cc559cf9dd81cb4b78b9116f99b6f884719a2d3"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.34.0" ]
revision = "708c06ea8f4330ce2221d5b2e53443dd6a480a2f"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.34.0" ]
revision = "b3ce89a0bda80631f7764d94afe17d4f11dbcd8b"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.34.0" ]
revision = "45da1b73825ea9578ebf10ffb4d930971f4369fe"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.34.0" ]
revision = "619d0ed758b351f2abd8845c191787869931b088"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.34.0" ]
revision = "fdfd364ad468b1c0a2cbac72ca56b7dd47914815"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.34.0" ]
revision = "3766ca5fadcf88ff0d0020d57d46a6d1591f0049"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.34.0" ]
revision = "a445c529654974ad6e292f62f98329c583416aba"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.34.0" ]
revision = "6472cccaada6772fc6803a3373596d95bca56c0c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.34.0" ]
revision = "ff133d13498b91a2219c32ace9c8c27331cb38c7"
